#!/usr/bin/env node
// format-report.mjs
// Takes the output of aggregate.mjs and produces a ranked markdown report.
//
// Usage: node format-report.mjs <aggregated.json> [--mode balanced] [--out report.md]

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

function formatReport(aggregated, { primaryMode = 'balanced' } = {}) {
  const { rankings, ideas_with_scores, combos, total_ideas, framework_version } = aggregated;
  const modes = Object.keys(rankings);
  const timestamp = new Date().toISOString().split('T')[0];

  const lines = [];
  lines.push(`# Project Evaluation Report — ${timestamp}`);
  lines.push('');
  lines.push(`Generated by \`project-evaluator\` plugin · framework v${framework_version} · ${total_ideas} ideas scored across 12 factors and 4 ranking modes.`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // TL;DR
  lines.push(`## TL;DR — Top 5 (${primaryMode} mode)`);
  lines.push('');
  const top5 = rankings[primaryMode].filter(x => !x._demoted).slice(0, 5);
  top5.forEach((entry, idx) => {
    lines.push(`${idx + 1}. **#${entry.id} ${entry.title}** (${entry.group_letter} ${entry.group_name}) — **${entry.score}%**`);
    lines.push(`   ${entry.justification || ''}`);
    lines.push('');
  });

  // Rankings under all 4 modes
  for (const mode of modes) {
    lines.push(`## Ranking — ${mode.charAt(0).toUpperCase() + mode.slice(1)} mode`);
    lines.push('');
    lines.push('| Rank | # | Title | Group | Score | Flags |');
    lines.push('|---:|---:|---|---|---:|---|');
    rankings[mode].slice(0, 20).forEach((entry, idx) => {
      const flags = (entry._flags && entry._flags.length) ? entry._flags.join(', ') : '';
      const marker = entry._demoted ? ' ⚠️ demoted' : '';
      lines.push(`| ${idx + 1} | ${entry.id} | ${entry.title} | ${entry.group_letter} ${entry.group_name ?? ''} | ${entry.score}${marker} | ${flags} |`);
    });
    lines.push('');
    lines.push('<details><summary>Show full ranking (all ideas)</summary>');
    lines.push('');
    lines.push('| Rank | # | Title | Score |');
    lines.push('|---:|---:|---|---:|');
    rankings[mode].forEach((entry, idx) => {
      const marker = entry._demoted ? ' ⚠️' : '';
      lines.push(`| ${idx + 1} | ${entry.id} | ${entry.title} | ${entry.score}${marker} |`);
    });
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Red flags report
  const flaggedIdeas = ideas_with_scores.filter(i => (i.red_flags || []).length > 0);
  lines.push(`## Red flags report (${flaggedIdeas.length} ideas flagged)`);
  lines.push('');
  if (flaggedIdeas.length === 0) {
    lines.push('_No red flags attached. This may indicate the framework is rubber-stamping — review carefully._');
  } else {
    lines.push('| # | Title | Flags | Justification |');
    lines.push('|---:|---|---|---|');
    flaggedIdeas.forEach(idea => {
      lines.push(`| ${idea.id} | ${idea.title} | ${(idea.red_flags || []).join(', ')} | ${idea.justification || ''} |`);
    });
  }
  lines.push('');

  // Portfolio combos
  lines.push('## Portfolio combos');
  lines.push('');
  for (const [key, combo] of Object.entries(combos)) {
    lines.push(`### ${combo.name}`);
    lines.push('');
    lines.push(`_${combo.rationale}_`);
    lines.push('');
    combo.picks.forEach((pick, idx) => {
      if (!pick) return;
      lines.push(`${idx + 1}. **#${pick.id} ${pick.title}** (${pick.group_letter || ''} ${pick.group_name || ''}) — balanced ${pick.balanced_score ?? pick.score ?? '?'}%`);
    });
    lines.push('');
  }

  // Per-idea detailed scoring appendix
  lines.push('## Appendix — full scoring per idea');
  lines.push('');
  lines.push('| # | Title | Demand | Effort | TechFit | Dist | Assets | Speed | TAM | Comp | Moat | Price | Diff | OpBur | Flags |');
  lines.push('|---:|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|---|');
  for (const idea of ideas_with_scores) {
    const fs = idea.factor_scores;
    const flags = (idea.red_flags || []).length > 0 ? '⚠️' : '';
    lines.push(
      `| ${idea.id} | ${idea.title} | ${fs.demand_evidence} | ${fs.build_effort} | ${fs.technical_fit} | ${fs.distribution_clarity} | ${fs.asset_leverage} | ${fs.time_to_first_revenue} | ${fs.tam} | ${fs.competition_density} | ${fs.moat} | ${fs.pricing_power} | ${fs.differentiator} | ${fs.operational_burden} | ${flags} |`
    );
  }
  lines.push('');

  // Decision tree
  lines.push('## Decision tree — which mode fits your current life stage?');
  lines.push('');
  lines.push('- **Need a paid user this month** → use **Cashflow** top 5');
  lines.push('- **Want to build a defensible single business** → use **Moat** top 5');
  lines.push('- **Building skills for a career pivot** → use **Learning** top 5');
  lines.push('- **Exploring, no strong constraint** → use **Balanced** top 5');
  lines.push('');

  return lines.join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const inputPath = args[0];
  const mode = args.includes('--mode') ? args[args.indexOf('--mode') + 1] : 'balanced';
  const outPath = args.includes('--out') ? args[args.indexOf('--out') + 1] : null;

  if (!inputPath) {
    console.error('Usage: node format-report.mjs <aggregated.json> [--mode M] [--out report.md]');
    process.exit(1);
  }
  const aggregated = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
  const markdown = formatReport(aggregated, { primaryMode: mode });
  if (outPath) {
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, markdown);
    process.stderr.write(`Wrote report → ${outPath}\n`);
  } else {
    process.stdout.write(markdown);
  }
}

if (process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}

export { formatReport };
